# The message that appears on the item.
# Make sure to end it with "%Name%"
ItemMessage: '&6Spawned in creative by %Name%'

# Rename the crafting result if its a spawned item
RenameCrafting: true

# The following does not effect creative mode. Only non-creative

# Prevent their using it to attack, defend, place, etc.
PreventUsage: true
# Prevent their using it to craft items
PreventCrafting: true
# Prevent using it in a anvil
PreventAnvil: true
# Prevent them from using the armour in survival mode
PreventArmor: true
# Mark blocks which are creative spawned in to drop creative spawned items.
MarkBlocks: true

# What worlds are disabled  for this.
# It means this plugin will ignore that world.
# Items carried over from that world WILL be usable.
# You will need to have another plugin to seperate inventories.
WorldsDisabled:
  - creativebuild
  - creativeplay
  
# With block/items will be disabled when in creative limited mode?
# Don't use ID's, only full NAME of item. Names can be found at http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html
DisabledItems: []
  
# Does the plugin save the marked blocks into a config? Overtime this may get.. laggy.
SaveBlocks: true

# Turn this to true if you wish to use mysql for the saveblocks. Else it will default to flatfile.
UseMysql: false
# You will need to enter your mysql details here.
MysqlHost: www.mydatabase.com
MysqlUsername: root
MysqlPassword: ilovecows
MysqlDatabase: database

# Does the plugin prevent creative items being transfered through inventories?
# Does it prevent creative items being dropped?
# Does it prevent creative items being picked up by non-creative players?
# Does it prevent non-creative items being picked up by creative?
# Does it delete all creative items dropped?
# Does it delete all non-creative items dropped? (Doesn't include entities such as exp orbs, fired arrows, etc. Just items)